# Generated by Django 3.2 on 2022-04-04 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAddress',
        ),
    ]
