# Generated by Django 3.2 on 2022-04-04 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_useraddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountextention',
            name='phone_is_verified',
        ),
        migrations.RemoveField(
            model_name='accountextention',
            name='phone_verification_link',
        ),
        migrations.RemoveField(
            model_name='accountextention',
            name='token_phone',
        ),
    ]
